language: php
php:
  - 5.3
  - 5.4
before_script:
  - composer install
  - echo "apc.enabled=1" >> `php --ini |grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - echo "apc.enable_cli=1" >> `php --ini |grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - phpenv rehash
script: phpunit
